version: '3.9'

services:
  job1:
    build:
      context: .
    environment:
      API_AUTH_TOKEN: ${API_AUTH_TOKEN}
    ports:
      - "8081:8081"
  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      API_AUTH_TOKEN: "test token since we do not perform requests to real data anyway"