[supervisord]
nodaemon=true

[program:job1]
command=gunicorn extractor_job:app -b 0.0.0.0:8081
directory=/app/lec02
autostart=true
autorestart=true

[program:job2]
command=gunicorn loader_job:app -b 0.0.0.0:8082
directory=/app/lec02
autostart=true
autorestart=true
